server:
  port: 8906

spring:
  datasource:
    url: jdbc:postgresql://pgsql/universe?currentSchema=milkyway
    username: postgres
    password: 123456

site:
  andromeda: http://andromeda:8906/andromeda
  carina: http://carina:8906/carina
  leob: http://leob:8906/leob
